class Commands:
    LEECH = "leech@flixlktorrentleechers"
    PURGE = "purge@flixlktorrentleechers"
    PAUSEALL = "pauseall@flixlktorrentleechers"
    RESUMEALL = "resumeall@flixlktorrentleechers"
    STATUS = "status@flixlktorrentleechers"
    SETTINGS = "settings@flixlktorrentleechers"
    EXEC = "exec@flixlktorrentleechers"
    UPLOAD = "upload@flixlktorrentleechers"
    YTDL = "ytdl@flixlktorrentleechers"
    PYTDL = "pytdl@flixlktorrentleechers"
    ABOUT = "about@flixlktorrentleechers"
    GETLOGS = "getlogs@flixlktorrentleechers"
    SERVER = "server@flixlktorrentleechers"
    USERSETTINGS = "usetting@flixlktorrentleechers"
    INSTADL = "instadl@flixlktorrentleechers"
