class Commands:
    LEECH = "leech@FlixLKTorrentLeech_Bot"
    PURGE = "purge@FlixLKTorrentLeech_Bot"
    PAUSEALL = "pauseall@FlixLKTorrentLeech_Bot"
    RESUMEALL = "resumeall@FlixLKTorrentLeech_Bot"
    STATUS = "status@FlixLKTorrentLeech_Bot"
    SETTINGS = "settings@FlixLKTorrentLeech_Bot"
    EXEC = "exec@FlixLKTorrentLeech_Bot"
    UPLOAD = "upload@FlixLKTorrentLeech_Bot"
    YTDL = "ytdl@FlixLKTorrentLeech_Bot"
    PYTDL = "pytdl@FlixLKTorrentLeech_Bot"
    ABOUT = "about@FlixLKTorrentLeech_Bot"
    GETLOGS = "getlogs@FlixLKTorrentLeech_Bot"
    SERVER = "server@FlixLKTorrentLeech_Bot"
    USERSETTINGS = "usetting@FlixLKTorrentLeech_Bot"
    INSTADL = "instadl@FlixLKTorrentLeech_Bot"
